services:
  - type: web
    name: community-sarcopenia-screening
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
